# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(db_column='nick_name', max_length=200, verbose_name='\u6635\u79f0')),
                ('premise', models.CharField(db_column='premise', max_length=100, verbose_name='\u6240\u5728\u5730')),
                ('gender', models.CharField(db_column='gender', max_length=10, verbose_name='\u6027\u522b')),
                ('birthday', models.CharField(db_column='birthday', max_length=60, verbose_name='\u751f\u65e5')),
                ('intro', models.TextField(db_column='intro', verbose_name='\u7b80\u4ecb')),
                ('registerTime', models.CharField(db_column='register_time', max_length=100, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('headerPath', models.CharField(db_column='header_path', max_length=500, verbose_name='\u5934\u50cf')),
                ('level', models.CharField(db_column='level', max_length=50, verbose_name='\u7b49\u7ea7')),
                ('badge', models.CharField(db_column='badge', max_length=50, verbose_name='\u52cb\u7ae0')),
                ('place', models.CharField(db_column='place', max_length=50, verbose_name='\u5173\u6ce8\u6570\u91cf')),
                ('fans', models.CharField(db_column='fans', max_length=50, verbose_name='\u7c89\u4e1d\u6570\u91cf')),
                ('blog', models.CharField(db_column='blog', max_length=50, verbose_name='\u5fae\u535a\u6570\u91cf')),
                ('sinaNo', models.CharField(db_column='sina_no', max_length=100, verbose_name='\u5fae\u535a\u7528\u6237\u7f16\u53f7')),
                ('referFlag', models.CharField(db_column='refer_flag', max_length=50, verbose_name='\u6807\u8bc6')),
                ('crTime', models.CharField(db_column='cr_time', max_length=100, verbose_name='\u83b7\u53d6\u65f6\u95f4')),
            ],
            options={
                'db_table': 'sina_user_info',
                'verbose_name': '\u65b0\u6d6a\u5fae\u535a\u7528\u6237\u4fe1\u606f',
            },
        ),
    ]
